# Generated by Django 3.2 on 2021-05-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_orderplaced_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='salt_composition',
            field=models.TextField(default='', max_length=80),
        ),
    ]
