# Generated by Django 3.2 on 2021-05-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_product_salt_composition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('D', 'Prescription Drug'), ('S', 'Suppliments'), ('MS', 'Medical Supplies'), ('M', 'Misc')], max_length=2),
        ),
    ]
